"""create employees table

Revision ID: c8546ecebb8b
Revises: 
Create Date: 2026-04-25 15:24:28.562465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8546ecebb8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_country', 'employees', ['country'], unique=False)
    op.create_index('idx_country_title', 'employees', ['country', 'job_title'], unique=False)
    op.create_index('idx_job_title', 'employees', ['job_title'], unique=False)
    op.create_index('idx_salary', 'employees', ['salary'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index('idx_salary', table_name='employees')
    op.drop_index('idx_job_title', table_name='employees')
    op.drop_index('idx_country_title', table_name='employees')
    op.drop_index('idx_country', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
